### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by jesseshieh** [NoRedInk/elm-rollbar#1]
Hi! This package looks like exactly what I need, but I can't seem to install it using
```
$ elm package install NoRedInk/elm-rollbar
Error: Could not find any packages named NoRedInk/elm-rollbar.

Here are some packages that have similar names:

    NoRedInk/elm-compare
    NoRedInk/elm-rails
    NoRedInk/elm-check
    NoRedInk/elm-phoenix

Maybe you want one of those?
```
What's the right way to install this package?

**Comment by aaronshim** [comment]
For the benefit of those who will stumble on this issue in the future, as was discussed on the #elmlang slack, we can't really install native packages without prior clearance from the elm packages repository, and it's best to roll your own Ports implementation to talk to the `rollbar.js` API.

**Comment by rtfeldman** [comment]
Actually rollbar.js is just exception-catching (not needed for Elm, plus vanilla rollbar.js is fine for that) and vanilla HTTP requests, so really there's no reason this library couldn't be written in plain old Elm. 😄

**Comment by aaronshim** [comment]
Is someone volunteering for the vanilla Elm rewrite? :stuck_out_tongue_closed_eyes:
