### ISSUE TITLE
Plans for Elm 0.19 support? 

### ISSUE THREAD

**Issue by jweir** [NoRedInk/elm-rollbar#4]
I'm looking to add Rollbar reporting to an Elm 0.19 application and considered upgrading this package, and I am happy to do so, unless,  that effort is already underway.

**Comment by rtfeldman** [comment]
A PR would be lovely, thank you! ❤️

**Comment by rtfeldman** [comment]
PR is merged, but not quite published yet - `elm publish` thinks this has never been published, so it wants me to overwrite the 0.18 `1.0.0` git tag, which would break the 0.18 package.

Currently talking through the best way to work around this!

**Comment by jweir** [comment]
Yeah, curious what the best path forward is regarding the version.  Also I pushed one more PR for a bit of code that didn't get merged.  Glad to help and will be happy to have this as a package.
